# Generated by Django 5.1.3 on 2025-10-31 09:21

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Employee ID"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("corporate_law", "Corporate Relocation"),
                            ("international", "International Relocation"),
                            ("domestic", "Domestic Relocation"),
                            ("family", "Family Relocation"),
                        ],
                        max_length=50,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="KE", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "expertise",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Areas of Expertise"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "max_clients",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Maximum Clients"
                    ),
                ),
                (
                    "current_client_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Current Client Count"
                    ),
                ),
                (
                    "work_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+254750000000",
                        max_length=30,
                        region=None,
                        verbose_name="Work Phone Number",
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Work Email"
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("busy", "Busy"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Availability Status",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+254700000000",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="KE", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "relocation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("corporate_law", "Corporate Relocation"),
                            ("international", "International Relocation"),
                            ("domestic", "Domestic Relocation"),
                            ("family", "Family Relocation"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Relocation Type",
                    ),
                ),
                (
                    "current_country",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current Country",
                    ),
                ),
                (
                    "current_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current City",
                    ),
                ),
                (
                    "destination_country",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Destination Country",
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Destination City",
                    ),
                ),
                (
                    "expected_relocation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Relocation Date"
                    ),
                ),
                (
                    "relocation_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Relocation Start Date"
                    ),
                ),
                (
                    "expected_move_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Move Date"
                    ),
                ),
                (
                    "family_members",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Number of Family Members"
                    ),
                ),
                (
                    "has_children",
                    models.BooleanField(default=False, verbose_name="Has Children"),
                ),
                (
                    "children_ages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Children Ages"
                    ),
                ),
                (
                    "housing_budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Housing Budget Minimum",
                    ),
                ),
                (
                    "housing_budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Housing Budget Maximum",
                    ),
                ),
                (
                    "preferred_neighborhoods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Preferred Neighborhoods"
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Preferred Contact Method",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Notification Preferences",
                    ),
                ),
                (
                    "overall_progress",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Overall Progress (%)"
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current Stage of Relocation",
                    ),
                ),
                (
                    "relocation_consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_clients",
                        to="profiles.consultant",
                        verbose_name="Relocation Consultant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="Document Type"),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="documents/", verbose_name="Document File"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("awaiting review", "Awaiting Review"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Document Status",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to="profiles.consultant",
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Task Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Task Description"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
