# Generated by Django 5.1.3 on 2025-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_task_options_task_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stage",
            field=models.CharField(
                choices=[
                    ("initial_consultation", "Initial Consultation"),
                    ("document_collection", "Document Collection"),
                    ("visa_processing", "Visa Processing"),
                    ("housing_search", "Housing Search"),
                    ("school_enrollment", "School Enrollment"),
                    ("final_relocation", "Final Relocation"),
                ],
                default="initial_consultation",
                max_length=50,
                verbose_name="Relocation Stage",
            ),
        ),
    ]
