# Generated by Django 5.1.3 on 2025-11-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_task_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_consultant",
            field=models.BooleanField(default=False, verbose_name="Is Consultant"),
        ),
    ]
