# Generated by Django 5.1.3 on 2025-11-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_is_consultant"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="is_consultant",
            field=models.BooleanField(default=True, verbose_name="Is Consultant"),
        ),
    ]
