#!/bin/bash

set -o errexit
set -o nounset

watchmedo auto-restart -d /django_app/real_estate/ -p "*.py" -- celery -A real_estate worker --loglevel=info

watchmedo auto-restart -d /django_app/real_estate/ -p "*.py" -- celery -A real_estate.celery_app beat -l info  


