#!/bin/bash

set -o errexit
set -o nounset


watchmedo auto-restart -d /django_app/backend/ -p "*.py" -- celery -A backend.celery_app worker --loglevel=info

watchmedo auto-restart -d /django_app/backend/ -p "*.py" -- celery -A backend.celery_app beat -l info  


